version: "2"
services:
  nginx:
    container_name: nginx-server
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodeapp
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nodeapp:
    container_name: nodeapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-server      
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"